import type { HealthDataset } from "./health-engine";

export const safeDemoData: HealthDataset = {
  profile: {
    label: "ملف تجريبي مجهول",
    ageBand: "35–44",
    lastSync: "18 يوليو 2026",
    source: "ساعة ذكية + سجل مختبر تجريبي + قائمة مكملات تجريبية",
  },
  goals: { steps: 10000, sleep: 7, workoutMinutes: 150 },
  cardiac: {
    maxJoggingHeartRate: 188,
    typicalJoggingPeak: 174,
    context: "ذروة مسجلة أثناء هرولة قوية في العينة المصطنعة؛ لا يتوفر تخطيط نظم تشخيصي.",
    source: "Synthetic wearable workout summary",
  },
  daily: [
    { date: "12 يول", steps: 6120, sleep: 6.1, workout: 18, restingHeartRate: 59 },
    { date: "13 يول", steps: 7840, sleep: 6.6, workout: 22, restingHeartRate: 58 },
    { date: "14 يول", steps: 10340, sleep: 7.2, workout: 34, restingHeartRate: 56 },
    { date: "15 يول", steps: 6950, sleep: 6.4, workout: 12, restingHeartRate: 58 },
    { date: "16 يول", steps: 11280, sleep: 7.5, workout: 38, restingHeartRate: 55 },
    { date: "17 يول", steps: 8420, sleep: 6.8, workout: 20, restingHeartRate: 57 },
    { date: "18 يول", steps: 9580, sleep: 7.1, workout: 31, restingHeartRate: 55 },
  ],
  labs: [
    {
      id: "ldl-demo",
      nameAr: "الكوليسترول الضار",
      nameEn: "LDL cholesterol",
      category: "الدهون",
      unit: "mg/dL",
      reference: "أقل من 100",
      status: "review",
      statusLabel: "للمراجعة",
      trend: "اتجاه هابط من 142 إلى 116، لكنه ما زال أعلى من مرجع العينة",
      clinicianQuestion: "هل الاتجاه الحالي كافٍ، وما موعد إعادة القياس الأنسب وفق عوامل الخطورة الشخصية؟",
      readings: [{ date: "يناير", value: 142 }, { date: "أبريل", value: 129 }, { date: "يوليو", value: 116 }],
    },
    {
      id: "vitamin-d-demo",
      nameAr: "فيتامين د",
      nameEn: "Vitamin D",
      category: "الفيتامينات",
      unit: "ng/mL",
      reference: "30–100",
      status: "good",
      statusLabel: "ضمن المرجع",
      trend: "تحسن تدريجي من 21 إلى 34 داخل النطاق المرجعي",
      clinicianQuestion: "ما خطة المتابعة التي تحافظ على النطاق دون تجاوز الجرعة المناسبة؟",
      readings: [{ date: "يناير", value: 21 }, { date: "أبريل", value: 27 }, { date: "يوليو", value: 34 }],
    },
    {
      id: "hba1c-demo",
      nameAr: "السكر التراكمي",
      nameEn: "HbA1c",
      category: "الأيض",
      unit: "%",
      reference: "أقل من 5.7",
      status: "good",
      statusLabel: "ضمن المرجع",
      trend: "مستقر مع تحسن بسيط من 5.6 إلى 5.4",
      clinicianQuestion: "هل يكفي تكرار القياس ضمن الفحص الدوري المعتاد؟",
      readings: [{ date: "يناير", value: 5.6 }, { date: "أبريل", value: 5.5 }, { date: "يوليو", value: 5.4 }],
    },
    {
      id: "ferritin-demo",
      nameAr: "مخزون الحديد",
      nameEn: "Ferritin",
      category: "الدم",
      unit: "ng/mL",
      reference: "30–300",
      status: "watch",
      statusLabel: "للمتابعة",
      trend: "انخفاض من 332 إلى 296 ووصول إلى الحد الأعلى من مرجع العينة",
      clinicianQuestion: "هل توجد حاجة لربط هذه القراءة ببقية مؤشرات الحديد أو الالتهاب؟",
      readings: [{ date: "يناير", value: 332 }, { date: "أبريل", value: 311 }, { date: "يوليو", value: 296 }],
    },
  ],
  supplements: [
    { name: "Vitamin D3", dose: "1000 IU", group: "الصباح", purpose: "سجل دعم فيتامين د", caution: "مراجعة الجرعة مع نتيجة فيتامين د والكالسيوم." },
    { name: "Omega‑3", dose: "1 g", group: "مع الوجبة", purpose: "سجل دعم غذائي", caution: "مناقشة الاستخدام عند تناول مميعات الدم أو قبل الإجراءات." },
    { name: "Creatine Monohydrate", dose: "3 g", group: "الصباح", purpose: "دعم التدريب المسجّل", caution: "مراجعة ملاءمته عند وجود مرض كلوي معروف." },
    { name: "Magnesium Glycinate", dose: "200 mg", group: "المساء", purpose: "روتين المساء", caution: "فصل التوقيت عن بعض الأدوية حسب إرشاد الصيدلي." },
    { name: "Psyllium Husk", dose: "5 g", group: "بعيدًا عن الأدوية", purpose: "رفع الألياف", caution: "يحتاج ماءً كافيًا وفاصلًا عن الأدوية الفموية." },
    { name: "Protein Powder", dose: "20 g", group: "بعد التمرين", purpose: "استكمال الاحتياج الغذائي", caution: "يُحسب ضمن الغذاء اليومي وليس بديلًا للوجبات." },
    { name: "Electrolyte Mix", dose: "1 serving", group: "بعد التمرين", purpose: "تعويض السوائل المسجّل", caution: "مراجعة الصوديوم عند وجود قيود طبية." },
    { name: "Vitamin B12", dose: "500 mcg", group: "الصباح", purpose: "سجل فيتامين", caution: "تقييم الحاجة الفعلية مع القياس والنمط الغذائي." },
  ],
};
